# YAML input file for SomaticSV
tumor:
  class: File
  path: ${TUMOR_BAM}
normal:
  class: File
  path: ${NORMAL_BAM}
reference:
  class: File
  path: ${REF_PATH}

# This is experimental, may be large. Right now, only for testing
generateEvidenceBam: true
#dryrun: false
