# TinDaisy template
# * complete workflow tindaisy.cwl 
# * production optimizations

# No reference- or collection-specific (e.g. CPTAC3) definitons

# Template for TinDaisy YAML input file
# The following arguments must be substituted:
# * NORMAL_BAM
# * TUMOR_BAM
# * REF_PATH
# * PARAM_ROOT -> value is $TD_ROOT/params
# * DBSNP_DB
# * VEP_CACHE_GZ
# * VEP_CACHE_VERSION
# * ASSEMBLY
# * CHRLIST
# * NORMAL_BARCODE
# * TUMOR_BARCODE

normal_bam:
  class: File
  path: NORMAL_BAM
tumor_bam:
  class: File
  path: TUMOR_BAM
reference_fasta:
  class: File
  path: REF_PATH

# barcodes replace "TUMOR" and "NORMAL" as sample names in output MAF 
normal_barcode: NORMAL_BARCODE
tumor_barcode: TUMOR_BARCODE

canonical_BED:  # type "File"
    class: File
    path: /gscuser/mwyczalk/projects/TinDaisy/TinDaisy/params/chrlist/GRCh38.callRegions.bed

# vcf (vaf length depth) filter config
pindel_vcf_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/vcf_filter_config-pindel.ini
strelka_vcf_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/vcf_filter_config-strelka.ini
varscan_vcf_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/vcf_filter_config-varscan.ini
mutect_vcf_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/vcf_filter_config-mutect.ini

# Caller config.  Note mutect does not have a caller config file
pindel_config:
  class: File
  path: PARAM_ROOT/caller_config/pindel.WES.ini
strelka_config:
  class: File
  path: PARAM_ROOT/caller_config/strelka.WES.ini
varscan_config:
  class: File
  path: PARAM_ROOT/caller_config/varscan.WES.ini

# Other filter config
classification_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/classification_filter_config.ini
af_filter_config:
  class: File
  path: PARAM_ROOT/filter_config/af_filter_config.ini

# Data files
centromere_bed: 
  class: File
  path: PARAM_ROOT/centromere/ucsc-centromere.GRCh38.bed

# See README.md for discussion of dbSnP references
dbsnp_db:
  class: File
  path: DBSNP_DB

# VEP Cache is used for VEP annotation and vcf_2_maf.
# If not defined, online lookups will be used by VEP annotation. These are slower and do not include allele frequency info (MAX_AF) needed by AF filter.
# For performance reasons, defining vep_cache_gz is suggested for production systems

vep_cache_gz:
  class: File
  path: VEP_CACHE_GZ

vep_cache_version: VEP_CACHE_VERSION
assembly: ASSEMBLY

chrlist: # Defining this turns on pindel parallel
  class: File
  path: CHRLIST


### YAML template as generated with cwltool --make-template
# can be found TinDaisy/cwl/workflows/template.tindaisy.yaml
