#!/bin/bash

# Matthew Wyczalkowski <m.wyczalkowski@wustl.edu>
# https://dinglab.wustl.edu/

# TODO: check if server is running / available and report reasonable error message
# TODO: implement -d debug output for all queries, based on get_output implementation

# TODO: 
#	* easily view status and disk usage stats for all workflows
# 	* Be able to run arbitrary commands on each workflow
# 	* Optionally print status in all queries


read -r -d '' USAGE <<'EOF'
Cromwell Query: Print out per-case run statistics. Specific to cromwell runs registered with MGI Cromwell database

Usage:
  cq [options] [ RID1 [RID2 ...] ]

Options:
-h: Print this help message
-d: Print debug output
-v: Indicate progress in stderr
-1: Stop after one
-k RUN_LIST: file with list of all run names, one per line, used when RUN_NAME1 not defined. Default: dat/RUN_LIST.dat
-q QUERY: type of query, one of 'check_server', 'status', 'logs', 'workflowRoot', 'timing', 'duration', 'outputs', 'runlog', 'url', 'du'.  Default is `status`
-s STEP: define step of interest for use with 'logs' query
-V: output query result only only (i.e., don't write case and workflow ID)
-U: skip cases were WorkflowID is Unknown or Unassigned
-S: retain only cases where Status is Succeeded
-T: Skip cases where logs are stashed 
-D: Do not access database.  Limited functionality: status is unknown, best guesses are made for other queries.  TODO: complete implementation
-C CROMWELL_URL: define the cromwell URL.  Default: http://mammoth.wusm.wustl.edu:8000
-L RUNLOG: Run log file. Default is "./logs/runlog.dat".  Can be obtained from environment variable

RID is RunID, and can be either a Run Name or a WorkflowID.  Examples:
* `cq` - will return status for all cases defined in `dat/RUN_LIST.dat`
* `cq CASE1 CASE2 CASE3` - returns status of runs for three cases.  TODO: discuss how this looked up
* `cq WID1 WID2` - returns status for two runs with given WorkflowIDs

If RID is - then read RID from STDIN.  If RID is not defined, read from first column of RUN_LIST file.

Evaluates the following information for each case
* The workflow ID of the cromwell job
* Various queries from https://genome-cromwell.gsc.wustl.edu/  Supported queries:
    * check_server - indicates whether server is running and accessible
    * status - Status of run
    * wid - Workflow ID
    * logs - List of stderr/stdout for each run.  All steps shown unless -s STEP is defined
    * workflowRoot - Path to root of cromwell output
    * timing - URL to visualize timing and progress of workflow
    * duration - display duration of run in minutes
    * outputs - All outputs of workflow run as specified in input CWL
    * runlog - Output status, start, end times
    * url - print URL of Cromwell server and quit.  This is a hardcoded value, but useful to know for manual queries
    * du - size of each workflow dir

Workflow ID associated with given cromwell output file is obtaining by grepping for output line like,
[2019-04-14 15:54:01,69] [info] SingleWorkflowRunnerActor: Workflow submitted d6c83416-af3f-46f3-a892-ff1e9074fe74

CROMWELL_URL can be defined as environment variable, e.g., `export CROMWELL_URL=http://mammoth.wusm.wustl.edu:8000
RUNLOG can be defined as environment variable, e.g., `export RUNLOG=/path/to/logs/runlog.dat`

Note that this script requires `jq` to be installed: https://stedolan.github.io/jq/download/
Also check to make sure cromwell server is running
EOF

source src/cromwell_utils.sh
SCRIPT=$(basename $0)   # used to identify this executable in error messages

# read default from environment variable if possible, otherwise use default
if [ -z $CROMWELL_URL ]; then
    CROMWELL_URL="https://genome-cromwell.gsc.wustl.edu"
#    CROMWELL_URL="http://mammoth.wusm.wustl.edu:8000"
fi
CURL_ARG="-k"   # arguments passed to all cromwell db calls 

# read default from environment variable if possible, otherwise use default
if [ -z $RUNLOG ]; then
    RUNLOG="./logs/runlog.dat"
fi

# Defaults
RUN_LIST="dat/RUN_LIST.dat"
QUERY="status"

# http://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":hdv1k:q:s:VUSTDC:L:" opt; do
  case $opt in
    h)
      echo "$USAGE"
      exit 0
      ;;
    d) 
      DEBUG=1
      ;;
    v) 
      PROGRESS=1
      ;;
    1) # Stop after 1
      JUST_ONCE=1
      ;;
    k) 
      RUN_LIST="$OPTARG"
      ;;
    q) 
      QUERY="$OPTARG"
      ;;
    s) 
      STEP="$OPTARG"
      ;;
    V) 
      STATUS_ONLY=1
      ;;
    U) 
      NO_UNKNOWN=1
      ;;
    S) 
      ONLY_SUCCESS=1      # What we all hope for
      ;;
    T) 
      NO_STASH=1
      ;;
    D) 
      NO_DB=1
      ;;
    C) 
      CROMWELL_URL="$OPTARG"
      ;;
    L) 
      RUNLOG="$OPTARG"
      ;;
    \?)
      >&2 echo "Invalid option: -$OPTARG"
      echo "$USAGE"
      exit 1
      ;;
    :)
      >&2 echo "Option -$OPTARG requires an argument."
      echo "$USAGE"
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

# If no DB, status is Unknown
function get_status {
    WID=$1

    if [ $NO_DB ]; then
        echo Unknown
        return
    fi
    URL="$CROMWELL_URL/api/workflows/v1/$WID/status"
    Q="curl $CURL_ARG -s -X GET $URL -H \"accept: application/json\" "
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_status Q = $Q
    fi
    R=$( eval $Q )
    test_exit_status $SCRIPT   # This seems like it fails uninformatively if db server not running
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_status R = $R
    fi

    # We validate JSON as recommended here: https://github.com/stedolan/jq/issues/1637
    if jq -e . >/dev/null 2>&1 <<<"$R"; then
        ERR=$(echo $R | jq -r '.errors[]? ')
        test_exit_status
    else
        ERR="$R"
    fi

    if [ ! -z $ERROR ]; then
        >&2 echo ERROR : $ERR
        exit 1
    fi

    # from /Users/mwyczalk/Projects/Rabix/somatic_sv_workflow/src/make_analysis_summary.sh
    # extract result path from YAML-format result file using `jq` utility, and confirm that it exists
    S=$( echo $R | jq -r '.status' )
    test_exit_status $SCRIPT
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_status S = $S
    fi
    echo $S
}

# If no DB, return Unknown (though may be able to guess)
function get_logs {
    WID=$1
    if [ $NO_DB ]; then
        echo Unknown
        return
    fi
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/logs" -H "accept: application/json" )
    test_exit_status $SCRIPT
    # from /Users/mwyczalk/Projects/Rabix/somatic_sv_workflow/src/make_analysis_summary.sh
    # extract result path from YAML-format result file using `jq` utility, and confirm that it exists
    if [ -z $STEP ]; then
        FILTER=".calls"
    else
        FILTER=".calls.${STEP}[0]"
    fi
    S=$( echo "$R" | jq -r "$FILTER" )
    test_exit_status $SCRIPT
    echo "$S"
}

function get_workflowRoot {
    WID=$1
    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/api/workflows/v1/$WID/metadata\" -H \"accept: application/json\" "
#   >&2 echo DEBUG: Q=$Q
    R=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" )
    test_exit_status $SCRIPT
#   >&2 echo DEBUG: R=$R
    S=$( echo "$R" | jq -r '.workflowRoot' )
    test_exit_status $SCRIPT
#   >&2 echo DEBUG: S=$S
    echo "$S"
}

# Get the directory size of each workflow as returned by du -sh
# If directory does not exist it is 0
function get_du {
	WID=$1

#    >&2 echo DEBUG: in get_du.  WID=$WID
	WR=$(get_workflowRoot $WID) 
#    >&2 echo DEBUG: WR = $WR
	if [ ! -d $WR ]; then
		echo "0"
        return
	fi
	CMD="du -sh $WR"

    eval $CMD
    test_exit_status $SCRIPT   

}

# This will return ALL outputs specified in CWL.  Note that this will consist of multiple lines
function get_outputs {
    WID=$1
    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/api/workflows/v1/$WID/outputs\" -H \"accept: application/json\" "
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_outputs Q = $Q
    fi

    R=$( eval $Q )
    test_exit_status $SCRIPT
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_outputs R = $R
    fi

    # Return all outputs which are not null
#    JQQ=".outputs[] | .location"
    # SomaticSV workflows have nested outputs, so use if/else to split
    # https://stackoverflow.com/questions/29949184/json-jq-if-without-else
    # https://programminghistorian.org/en/lessons/json-and-jq
    JQQ='.outputs[] | if (type == "array") then .[].location else .location end'
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_outputs JQQ = $JQQ
    fi
    S=$( echo "$R" | jq -r "$JQQ" )
    test_exit_status $SCRIPT

    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: get_outputs S = $S
    fi
    echo "$S"
}

# runlog returns the fields,
# status, start, end
function get_runlog {
    WID=$1
    STATUS=$(get_status $WID)
    test_exit_status $SCRIPT

    START=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" | jq -r '.start')
    test_exit_status $SCRIPT
    END=$( curl $CURL_ARG -s -X GET "$CROMWELL_URL/api/workflows/v1/$WID/metadata" -H "accept: application/json" | jq -r '.end')
    test_exit_status $SCRIPT
    printf "$STATUS\t$START\t$END"
}

# note that this does not require Run ID to be known
function check_server {

#    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/api/workflows/v1/$WID/outputs\" -H \"accept: application/json\" "

    Q="curl $CURL_ARG -s -X GET \"$CROMWELL_URL/engine/v1/version\" -H \"accept: application/json\"  "
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: check_server Q = $Q
    fi

# If server is running
    R=$( eval $Q )
    RC=$?
#    test_exit_status $SCRIPT
    if [ "$DEBUG" ]; then
        >&2 echo DEBUG: check_server status \$R = $R , return code = $RC 
    fi

    if [ $RC == 0 ]; then
        printf "OK"
    else
        printf "ERROR"
    fi
}

# duration returns the fields,
# status, run_duration_minutes
function get_duration {
    WID=$1
    RUNLOG=$(get_runlog $WID)
    test_exit_status 

    STATUS=$(echo "$RUNLOG" | cut -f 1)
    START=$(echo "$RUNLOG" | cut -f 2)
    END=$(echo "$RUNLOG" | cut -f 3)

# Duration calculation : https://stackoverflow.com/questions/14309032/bash-script-difference-in-minutes-between-two-times
    START_NUM=$(date -d $START +%s)
    END_NUM=$(date -d $END +%s)

    DIFF=$(( (END_NUM - START_NUM) / 60))

    printf "$STATUS\t$DIFF"
}

# Preliminary testing to make sure we can run:
# * make sure `jq` is available
# * test to make sure server running (unless query is check_server, which returns success)
# Confirm that `jq` is available
# from https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
# This may happen if running outside of CromwellRunner container
command -v jq >/dev/null 2>&1 || { echo >&2 "ERROR: jq is not installed.  Quitting"; exit 1; }
if [ $DEBUG ]; then
    >&2 echo DEBUG: jq OK
fi

# checking if server is running does not require information about cases or workflow IDs, so can be done immediately
STATUS=$(check_server)
if [ "$QUERY" == 'check_server' ]; then
    STATUS=$(check_server)
    >&2 echo $STATUS
    exit 0
elif [ "$STATUS" != "OK" ]; then
    >&2 echo ERROR: Cromwell server does not seem to be running
    exit 1
fi
if [ $DEBUG ]; then
    >&2 echo DEBUG: check_server OK
fi


# this allows us to get Run IDs in one of three ways:
# 1: cq RID1 RID2 ...
# 2: cat RUN_LIST.dat | cq -
# 3: read from RUN_LIST file
# Note that if no Run IDs defined, assume RIDS='-'
if [ "$#" == 0 ]; then
    confirm $RUN_LIST
    RIDS=$(cat $RUN_LIST | cut -f 1)
elif [ "$1" == "-" ] ; then
    RIDS=$(cat - )
else
    RIDS="$@"
fi

# REquire RUNLOG be defined, but it need not exist
#if [ ! -f $RUNLOG ]; then
#    >&2 echo ERROR: RUNLOG file $RUNLOG does not exist
#    exit 1
#fi

# loop over all cases, obtain WID and database status
# If log file does not exist, assume that the run has not started
# RID (run ID) may be either CASE or WorkflowID
for RID in $RIDS; do

    # Skip comments
    [[ $RID = \#* ]] && continue

    # https://stackoverflow.com/questions/2488715/idioms-for-returning-multiple-values-in-shell-scripting
    read CASE WID < <( getCaseWID $RID $RUNLOG )
    test_exit_status $SCRIPT

    if [ "$PROGRESS" ]; then
        >&2 echo Processing $CASE $WID
    fi

    if [ "$ONLY_SUCCESS" ]; then
        STATUS=$( get_status $WID )
        test_exit_status $SCRIPT
        if [ $STATUS != "Succeeded" ]; then
            continue
        fi
    fi

    # Skip runs which are stashed, i.e. those whose logs have been moved to directory logs/WorkflowID
    if [ $NO_STASH ]; then
        ISS=$(isStashed $RID)
        test_exit_status $SCRIPT
        if [ $ISS == 1 ]; then
            continue
        fi
    fi

    # Get status for various queries, but avoid db queries to server if WID unknown / unassigned
    if [[ $WID == "Unknown" ]] || [[ $WID == "Unassigned" ]]; then
        if [ "$NO_UNKNOWN" ]; then
            continue
        fi
        STATUS="Unknown"
    else
        if [ "$QUERY" == 'logs' ]; then
            STATUS=$(get_logs $WID)
            test_exit_status $SCRIPT
            STATUS=$(printf "\n$STATUS")
        elif [ "$QUERY" == 'status' ]; then
            STATUS=$(get_status $WID)
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'wid' ]; then
            STATUS=$WID
        elif [ "$QUERY" == 'workflowRoot' ]; then
            STATUS=$(get_workflowRoot $WID)
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'duration' ]; then
            STATUS=$(get_duration $WID)
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'timing' ]; then
            # URL as provided by tmooney on slack 
            STATUS="$CROMWELL_URL/api/workflows/v1/$WID/timing"
        elif [ "$QUERY" == 'outputs' ]; then    # this returns multiple outputs
            STATUS=$(get_outputs $WID | grep -v -w "null")
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'runlog' ]; then
            STATUS=$(get_runlog $WID)
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'du' ]; then
            STATUS=$(get_du $WID)
            test_exit_status $SCRIPT
        elif [ "$QUERY" == 'url' ]; then
            echo $CROMWELL_URL
            exit 0
        else 
            >&2 echo ERROR: Unknown query $QUERY
            >&2 echo "$USAGE"
            exit 1
        fi
    fi

    # Note that STATUS can have one or multiple lines (in the case of outputs query).  Awk deals with this correctly
    if [ -z $STATUS_ONLY ]; then
        echo "$STATUS" | awk -v c=$CASE -v w=$WID '{OFS="\t"}{print c,w,$0}'
    else
        printf "$STATUS\n" 
    fi

    if [ $JUST_ONCE ]; then
        >&2 echo Stopping after one
        break
    fi

done 




